/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7;

import static java.time.zone.ZoneRulesProvider.refresh;
import javax.swing.*;

/**
 *
 * @author HP
 */
public class BrowseCoursesFrame extends javax.swing.JFrame {

   private DefaultListModel<String> model;
   
    public BrowseCoursesFrame() {
         initComponents();
        model = new DefaultListModel<>();
        courseList.setModel(model);
        refresh();
        setTitle("Browse Courses");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BrowseCoursesFrame = new javax.swing.JLabel();
        enroll = new javax.swing.JButton();
        viewLessons = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BrowseCoursesFrame.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        BrowseCoursesFrame.setText("Browse Courses");

        enroll.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        enroll.setText("Enroll");
        enroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollActionPerformed(evt);
            }
        });

        viewLessons.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        viewLessons.setText("View Lessons");
        viewLessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLessonsActionPerformed(evt);
            }
        });

        courseList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(courseList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addComponent(BrowseCoursesFrame)
                .addGap(270, 270, 270))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(viewLessons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(320, 320, 320))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(BrowseCoursesFrame)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(enroll)
                        .addGap(48, 48, 48)
                        .addComponent(viewLessons)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollActionPerformed
        int index = courseList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course.");
            return;
        }

        CourseManagement c = CourseDatabase.courses.get(index);

        String studentId = JOptionPane.showInputDialog(this, "Enter Your Student ID:");
        if (studentId == null || studentId.trim().isEmpty()) return;

        c.enrollStudent(studentId);
        JOptionPane.showMessageDialog(this, "Enrolled Successfully!");           
    }//GEN-LAST:event_enrollActionPerformed

    private void viewLessonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLessonsActionPerformed
        int index = courseList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Select a course first.");
            return;
        }

        new ViewLessonsFrame(CourseDatabase.courses.get(index)).setVisible(true);
    }//GEN-LAST:event_viewLessonsActionPerformed
 
       private void refresh() {
        model.clear();
        for (CourseManagement c : CourseDatabase.courses) {
            model.addElement(c.getTitle());
        }
    }
       
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BrowseCoursesFrame;
    private javax.swing.JList<String> courseList;
    private javax.swing.JButton enroll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewLessons;
    // End of variables declaration//GEN-END:variables
}
