/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7;

import javax.swing.*;

/**
 *
 * @author HP
 */
public class ManageCoursesFrame extends javax.swing.JFrame {

  
    private DefaultListModel<String> model;
    private CourseDatabase courseDB;   

    public ManageCoursesFrame(CourseDatabase db) {
        this.courseDB = db;
        initComponents();
        model = new DefaultListModel<>();
        courseList.setModel(model);
        refreshList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addCourse = new javax.swing.JButton();
        manageLessons = new javax.swing.JButton();
        viewStudents = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel1.setText("Manage Courses");

        addCourse.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 18)); // NOI18N
        addCourse.setText("Add Course");
        addCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseActionPerformed(evt);
            }
        });

        manageLessons.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        manageLessons.setText("Manage Lessons");
        manageLessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageLessonsActionPerformed(evt);
            }
        });

        viewStudents.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        viewStudents.setText("View Students");
        viewStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentsActionPerformed(evt);
            }
        });

        courseList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(courseList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageLessons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(121, 269, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(addCourse)
                        .addGap(37, 37, 37)
                        .addComponent(manageLessons)
                        .addGap(44, 44, 44)
                        .addComponent(viewStudents))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseActionPerformed
        addCourse();
    }//GEN-LAST:event_addCourseActionPerformed

    private void manageLessonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageLessonsActionPerformed
        openLessonManager();
    }//GEN-LAST:event_manageLessonsActionPerformed

    private void viewStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentsActionPerformed
        openStudentsView();
    }//GEN-LAST:event_viewStudentsActionPerformed

    private void addCourse() {
       String id = JOptionPane.showInputDialog("Enter Course ID:");
        if (id == null || id.trim().isEmpty()) return;

        String title = JOptionPane.showInputDialog("Enter Title:");
        if (title == null || title.trim().isEmpty()) return;

        String desc = JOptionPane.showInputDialog("Enter Description:");
        if (desc == null || desc.trim().isEmpty()) return;

        try {
            Course c = new Course(id, title, desc, "inst1");
            courseDB.addCourse(c);
            refreshList();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    } 
    
    private void openLessonManager() {
         int index = courseList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course.");
            return;
        }

        Course selected = courseDB.getAllCourses().get(index);

        new ManageLessonsFrame(selected, courseDB).setVisible(true);
    }

       private void openStudentsView() {
         int index = courseList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course.");
            return;
        }

        Course selected = courseDB.getAllCourses().get(index);

        new ViewStudentsFrame(selected).setVisible(true);
    } 
        private void refreshList() {
        model.clear();
        for (Course c : courseDB.getAllCourses()) {
            model.addElement(c.getCourseId() + ": " + c.getTitle());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourse;
    private javax.swing.JList<String> courseList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageLessons;
    private javax.swing.JButton viewStudents;
    // End of variables declaration//GEN-END:variables
}
