/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7;

import javax.swing.*;

/**
 *
 * @author HP
 */
public class ManageLessonsFrame extends javax.swing.JFrame {

   private CourseManagement course;
    private DefaultListModel<String> model;
    
    public ManageLessonsFrame() {
        this.course = course;
        initComponents();

        model = new DefaultListModel<>();
        lessonList.setModel(model);

        refreshLessons();
        setTitle("Manage Lessons for: " + course.getTitle());
    }

    ManageLessonsFrame(CourseManagement selectedCourse) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        deleteLesson = new javax.swing.JButton();
        addLesson1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lessonList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel1.setText("Manage Lessons");

        deleteLesson.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        deleteLesson.setText("Delete Lesson");
        deleteLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLessonActionPerformed(evt);
            }
        });

        addLesson1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        addLesson1.setText("Add Lesson");
        addLesson1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLesson1ActionPerformed(evt);
            }
        });

        lessonList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lessonList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteLesson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addLesson1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(133, 270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(addLesson1)
                        .addGap(40, 40, 40)
                        .addComponent(deleteLesson)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLessonActionPerformed
        deleteLesson();
    }//GEN-LAST:event_deleteLessonActionPerformed

    private void addLesson1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLesson1ActionPerformed
        addLesson();
    }//GEN-LAST:event_addLesson1ActionPerformed

    private void refreshLessons() {
        model.clear();
        for (Lesson l : course.getLessons()) {
            model.addElement(l.getLessonId() + ": " + l.getTitle());
        }
    }

    private void addLesson() {
        String id = JOptionPane.showInputDialog(this, "Lesson ID:");
        if (id == null || id.trim().isEmpty()) return;

        String title = JOptionPane.showInputDialog(this, "Lesson Title:");
        if (title == null || title.trim().isEmpty()) return;

        String content = JOptionPane.showInputDialog(this, "Lesson Content:");
        if (content == null || content.trim().isEmpty()) return;

        try {
            Lesson lesson = new Lesson(id, title, content);
            course.addLesson(lesson);
            refreshLessons();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void deleteLesson() {
        int index = lessonList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Please select a lesson.");
            return;
        }

        String id = course.getLessons().get(index).getLessonId();
        course.removeLesson(id);
        refreshLessons();
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLesson1;
    private javax.swing.JButton deleteLesson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lessonList;
    // End of variables declaration//GEN-END:variables
}
